### ISSUE TITLE
noOptionsFound event is not working

### ISSUE THREAD

**Issue by Moggieggwp** [basvandenberg/angular2-select#103]
Hi, you are added 'noOptionsFound' event but i can't use it or it's not working.

                      ` <ng-select style="width: 300px;"

                                       [allowClear]="true"

                                       [options]="options"

                                       (selected)="someMethod1($event)"

                                       (deselected)="someMethod2($event)"

                                       (noOptionsFound)="search($event)"

                                       [disabled]="false">

                            </ng-select>`
I'm use 1.0.0-beta.2 version. In which version you are released it? or planning?

**Comment by basvandenberg** [comment]
Sorry, I shouldn't have added that to README.md yet... So this will be released in beta.3, hopefully today.

**Comment by basvandenberg** [comment]
1.0.0-beta.3 is released.

**Comment by Moggieggwp** [comment]
Thank you:)
