### ISSUE TITLE
multiple select value should be empty array, and not empty string

### ISSUE THREAD

**Issue by DethAriel** [basvandenberg/angular2-select#104]
Based on https://github.com/basvandenberg/angular2-select/blob/master/src/select.component.ts#L244 if the control is in "multiple" mode and has no values, the control value will be `""`, whereas `[]` is expected

**Comment by DethAriel** [comment]
Since the `required` angular validator will work with empty arrays as well as with empty strings (see [here](https://github.com/angular/angular/blob/7b7ae5fe56dd05a28821b5324e7d7863247bacee/modules/%40angular/forms/src/validators.ts#L18)), there should probably be no issues

**Comment by basvandenberg** [comment]
Good to hear that they have updated it. When I implemented it the `required` validator did not consider an empty array to be an empty value. Thanks for reporting this @DethAriel !
