### ISSUE TITLE
Error: (SystemJS) ctorParameters.map is not a function

### ISSUE THREAD

**Issue by ivesingh93** [basvandenberg/angular2-select#111]
I have followed the instructions from here: https://www.npmjs.com/package/angular2-select but still getting this error. Please let me know what am I missing?

**Comment by JunusErgin** [comment]
It seems that your angular version is too old. Update the @angular versions in your package.json and you'll be fine. Change your @angular packages like the following:

    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0"

**Comment by basvandenberg** [comment]
Duplicate #65
