### ISSUE TITLE
How to get selected value onChange

### ISSUE THREAD

**Issue by pranavsreedhar92** [basvandenberg/angular2-select#117]
How to get selected value onChange.

**Comment by pksatish07** [comment]
Put this code in constructor if you are using model based form
this.form.controls['controlName'].valueChanges.subscribe(
            (value: any) => { console.log("Value:", value);
}

**Comment by matthewhegarty** [comment]
There is also a `selected` event that fires on change.
```
<ng-select
...
    (selected)="lastEvent='selected ' + $event.label"
...
</ng-select>
```

See also the *Respond to (de)selected events* section of the [example page](https://basvandenberg.github.io/angular2-select/).

**Comment by pranavsreedhar92** [comment]
Thanks it worked.
