### ISSUE TITLE
angular2-select is not filling with the dynamic data

### ISSUE THREAD

**Issue by ermarkar** [basvandenberg/angular2-select#128]
On html
```
<ng-select [options]="users" [multiple]="true" [(ngModel)]="group.selectedUsers" placeholder="select users" name="users"></ng-select>
```
And I am filling with this API response data
```
ngOnInit() {
   this.userService.getAllUsers()
       .subscribe(data => {
            data.forEach(element => {
                this.users.push({ value: element.id, label: element.firstName});
            });
        })
}
```
Now the first time I open the add group page the user list is empty. The user list is filled after I open it the second time. Am I missing something?

https://stackoverflow.com/questions/42360819/angular2-select-is-not-filling-with-the-dynamic-data

**Comment by basvandenberg** [comment]
See response on stackoverflow, please do not post question here, this is for reporting issues only.
