### ISSUE TITLE
Select option - Can be mapped value label to another object property 

### ISSUE THREAD

**Issue by diegounanue** [basvandenberg/angular2-select#14]
I have an object that has two properties id and name. Is there any way to specify two properties as value and label? Or do I have to map the object properties id to value and name to label?

**Comment by basvandenberg** [comment]
I am not really in favor of this feature. With the map function you can easily map your list to the list that is accepted as input:

```
let selectOptions = yourOptions.map((option) => {
    return {
        value: option.id,
        label: option.name
    };
});
```

To me it sounds a little odd to offer customization of the input data structure like this. Also, I can't think of any other components that offer such a feature. But I might be wrong about that.

For now I will close this feature request. If there seems to be a large interest for this feature from other users, then I might consider implementing.
