### ISSUE TITLE
Preselecting values

### ISSUE THREAD

**Issue by kreilinger** [basvandenberg/angular2-select#15]
Hi,

how do I preselect values in multiple-mode? I am trying to build a filter-interface and I want it to preselect some options depending on the users settings.

Markus

**Comment by basvandenberg** [comment]
Hi Markus,

When your select component is part of a form, you can set the values by using the controls's `setValue` method: 

```
// In some initialization function.
this.form = new FormGroup({});
this.form.addControl('selectControl', new FormControl(''));

// Somewhere later on, preselect your options.
let values = ['a', 'b', 'c'];
form.controls['selectControl'].setValue(values);
```

There is no API function yet for setting a list of values outside of a form. This will be added later.

**Comment by kreilinger** [comment]
Hi Bastiaan,

 

thanks for your reply. I tried setting the controls value with .setValue with a definitly existing and filled array, but all I get is this error:

 

core.umd.js:3468 TypeError: Cannot set property 'selected' of undefined

    at SelectComponent.writeValue (http://localhost:8080/node_modules/angular2-select/src/select.component.js:247:29)

    at eval (http://localhost:8080/node_modules/@angular/forms/bundles/forms.umd.js:1481:31)

    at eval (http://localhost:8080/node_modules/@angular/forms/bundles/forms.umd.js:2511:69)

    at Array.forEach (native)

    at FormControl.setValue (http://localhost:8080/node_modules/@angular/forms/bundles/forms.umd.js:2511:32)

    at DocumentationListComponent.presetCategories (http://localhost:8080/app/components/documentation-list.component.js:88:19)

    at eval (http://localhost:8080/app/components/documentation-list.component.js:121:55)

    at ZoneDelegate.invokeTask (http://localhost:8080/node_modules/zone.js/dist/zone.js:236:37)

    at Object.onInvokeTask (http://localhost:8080/node_modules/@angular/core/bundles/core.umd.js:6233:41)

    at ZoneDelegate.invokeTask (http://localhost:8080/node_modules/zone.js/dist/zone.js:235:42)

 

Do you have any idea whats happening here?

 

Von: Bastiaan van den Berg <notifications@github.com>
Antworten an: basvandenberg/angular2-select <reply@reply.github.com>
Datum: Dienstag, 4. Oktober 2016 um 10:46
An: basvandenberg/angular2-select <angular2-select@noreply.github.com>
Cc: kreilinger <strauss3@gmx.at>, Author <author@noreply.github.com>
Betreff: Re: [basvandenberg/angular2-select] Preselecting values (#15)

 

Hi Markus,

When your select component is part of a form, you can set the values by using the controls's setValue method: 
// In some initialization function.
this.form = new FormGroup({});
this.form.addControl('selectControl', new FormControl(''));
 
// Somewhere later on, preselect your options.
let values = ['a', 'b', 'c'];
form.controls['selectControl'].setValue(values);
There is no API function yet for setting a list of values outside of a form. This will be added later.

**Comment by basvandenberg** [comment]
First, make sure your are running the latest angular2-select version:

```
npm install --save angular2-select@latest
```

The error indicates that one of the values in the list that you provided to the `setValue` function could not be found in the list of options. Please double check if the values correspond to those in your list of select options.

Last thing I can think of. Could it be that you set the values while the select component is not yet initialized? Not sure if that's possible at all.

A code example of what causes the error would be very helpful to debug this. From this error alone I cannot tell if there's a bug in the select source, or if something is wrong in your code.

**Comment by ovaiskhan11** [comment]
@basvandenberg, same error its showing in my scenario but its not for multiple select. I have also updated latest version. Please check the below example.
**HTML:** 
```
<ng-select 
	[options]="jobOptions"
	multiple="false"
	placeholder="Select Job"
	formControlName="selectJob"
	[allowClear]="true">
</ng-select>
```
**Component:**

```
export class FormRender implements OnInit {
	jobOptions: Array<any> = [];
	
	renderForm: FormGroup;
	
	private fetchData():void {
        this.jobOptions = [
            {value: '1', label: 'Alpha'},
            {value: '2', label: 'Beta'},
            {value: '3', label: 'Gamma'},
        ]
    } 
	
	private preSelectedData():void {
        this.renderForm.controls['selectJob'].setValue('3');
    }
	
	ngOnInit():void {
		this.fetchData();
		this.renderForm = new FormGroup({});
		this.renderForm.addControl('selectJob', new FormControl());
		this.preSelectedData();
	}
}
```
Do you have any idea?

**Comment by basvandenberg** [comment]
What if you call `this.preSelectedData()` in the `ngAfterViewInit`? In `ngOnInit` the child components (the select component is a child component in this case) might not have been initialized yet, while this is guaranteed in `ngAfterViewInit`.

```
import {Component, OnInit, AfterViewInit}

export class FormRender implements OnInit, AfterViewInit {
    jobOptions: Array<any> = [];

    renderForm: FormGroup;

    private fetchData():void {
        this.jobOptions = [
            {value: '1', label: 'Alpha'},
            {value: '2', label: 'Beta'},
            {value: '3', label: 'Gamma'},
        ]
    } 

    private preSelectedData():void {
        this.renderForm.controls['selectJob'].setValue('3');
    }

    ngOnInit():void {
        this.fetchData();
        this.renderForm = new FormGroup({});
        this.renderForm.addControl('selectJob', new FormControl());
    }

    ngAfterViewInit() {
        this.preSelectedData();
    }
}
```
Another option is to provide the value to the FormControl constructor, that should work in `ngOnInit`:

```
    ngOnInit():void {
        this.fetchData();
        this.renderForm = new FormGroup({});
        this.renderForm.addControl('selectJob', new FormControl('3'));
    }
```

**Comment by basvandenberg** [comment]
Just tried the `ngAfterViewInit` in a plunker, but it throws another error...

**Comment by basvandenberg** [comment]
With `ngAfterViewInit` I get the often occuring 'Expression has changed after it was checked' error, which can be resolved with a timeout:
```
    ngAfterViewInit() {
        setTimeout(() => {
          this.form.controls['selectSingle'].setValue('3');
        }, 0);
    }
```

**Comment by basvandenberg** [comment]
By the way, using `setValue` in `ngOnInit` does work in the [plunker](https://plnkr.co/edit/PeGmCwVmi1X8Ag7LgnPT?p=preview). That example looks pretty much the same as your code.

**Comment by ovaiskhan11** [comment]
@basvandenberg thanks for your help. I have fixed the issue by using `setTimeout`. One more question can you please tell me how I can check my data render in the html. For example: I have variable`this.jobOptions` which is an array. I have made call to service and got the data. I pushed the data to the variable `this.jobOptions`.
So how I can detect variable `this.jobOptions` render the options of `<ng-select>`? and Can I make `<ng-select>` as a required field?
Waiting for your positive response.

**Comment by basvandenberg** [comment]
I am not sure if I understand your first question. Are you looking for a life cycle hook like [ngAfterViewChecked](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#afterview)?

You can make ng-select required by using the required [validator](https://angular.io/docs/ts/latest/api/forms/index/Validators-class.html):

```
import {Validators} from '@angular/forms';
```
...
```
    this.renderForm.addControl('selectJob', new FormControl(), Validators.required);
```

In this case the `valid` property of your form object will be false as long as the user did not select an option.

**Comment by guillermo-serfe** [comment]
Hello,

I'm using multiple-mode. It's mandatory that the options must be set on OnInit function to be preselected? Because I need to load them after as they are returned from an API. 

The options are loaded OK, but I can't preselect initial values. 

I tried with ngModel and calling directly to the select() function from select.component but I couldn't do it.

Thanks in advance!
