### ISSUE TITLE
how i can set default value ?

### ISSUE THREAD

**Issue by JorgeOrtizG** [basvandenberg/angular2-select#17]
I need set default item selected

**Comment by h284611** [comment]
I take a quick look at 3 functions (i.e., init, initOptions, and initDefaults) and I guess it doesn't support the default selected item as of today. 

Correct me if I am wrong.

**Comment by wladimiravila** [comment]
hi guys, I have the same problem :( some answer?

**Comment by basvandenberg** [comment]
I am not sure if I correctly understand the specifications of the feature you are asking for. Could you give a bit more detailed explanation about this feature request? Is there a comparable option for the jQuery select2 or selectize plugin?

Within a form you can set initial values by providing a list of values to the FormControl (Although I noticed that this doesn't work correctly with the single select at the moment...).

```
   ngOnInit() {
        this.form = new FormGroup({});
        this.form.addControl('selectMultiple', new FormControl(['2', '22']));
    }
```

**Comment by matthewhegarty** [comment]
There is a use-case where I would need to set the value of the select dynamically.  If I am loading a persisted object for display in a form (ie 'edit details'), then I would want to load the record, and then set all form fields according to the values within the record.

In HTML you could do this but putting **selected** onto the relevant option:

```
<select>
<option value="1">A</option>
<option value="2" selected>B</option>
<option value="3">C</option>
</select>
```

It seems select2 can do this: see [here](http://stackoverflow.com/questions/16969666/jquery-select2-set-default-value-from-an-option-in-list)

I tried using `[(ngModel)]` to bind to a selected object, which is how this is done in the [Angular docs](https://angular.io/docs/ts/latest/guide/forms.html), but that doesn't work for angular2-select.

So there needs to be a way that the selected value can be set at any point during the lifecycle of the component.

**Comment by basvandenberg** [comment]
In a form you can indeed set the values through the select's `FormControl`. As mentioned before, this can be done during initialization when building your `FormGroup` object:
```
    ngOnInit() {
        this.form = new FormGroup({});
        this.form.addControl('theSelect', new FormControl(['valueA', 'valueD', 'someOtherValue']));
    }
```
This sets the value (an array of select values `['valueA', 'valueD', ...]`) of a multiselect. For a single select you need to provide a string (`new FormControl('valueA')`).

You can after initialization indeed also use the control's [`setValue`](https://angular.io/docs/ts/latest/api/forms/index/FormControl-class.html#!#setValue-anchor) and [`patchValue`](https://angular.io/docs/ts/latest/api/forms/index/FormControl-class.html#!#patchValue-anchor) methods:
```
this.form.controls['theSelect'].setValue(['valueA', 'valueC', 'valueZ']);
```
Or for single select:
```
this.form.controls['theSelect'].setValue('valueE');
```
As far as I know this is the common use of [reactive forms](https://angular.io/docs/ts/latest/api/forms/index/ReactiveFormsModule-class.html).

I haven't tested the use of two-way data-binding with `ngModel` yet (which is as far as I know the common use of template driven [forms](https://angular.io/docs/ts/latest/api/forms/index/FormsModule-class.html)). I will have a look at that later.

**Comment by dcoli** [comment]
I'm having trouble getting this to work. What's happening is that I'm passing in the *values* of the options I was preselected, and instead the this.optionsDict object has no properties with those values as keys.

```
    this.form = new FormGroup({});
    this.form.addControl('topicSelect', new FormControl(['909', '1572']));
    //also tried this.form.controls['theSelect'].setValue([{ value:'909',label:'Bankruptcy' }]);

```
`core.umd.js:3257 EXCEPTION: Cannot set property 'selected' of undefined`

Even though I'm getting this error, the control loads fine and can be used without apparent problems. It just throws the error and doesn't preselect the options.

**Comment by KyleCartmell** [comment]
This component is working fine for me within a template-driven form. (alpha 12)

**Comment by dcoli** [comment]
I'm not sure if my problem is with the component or if there's something wrong with my understanding of when things should be fired. 

```
      <form [formGroup]="form">
      <ng-select
        [options] = "this.selectOptions"
        [multiple] = "this.showMultiple"
        placeholder = "Select topics"
        [allowClear] = "true"
        theme = "default"
        (selected) = "onSelected( $event )"
        (deselected) = "onDeselected( $event )"
        formControlName = "topicSelect">
      </ng-select>
      </form>
```

Departing from the canonical you gave above, I'm trying to setValue based on the results of a service call. So I'm initializing the form here, where getContentItems is the service call:

```
  ngOnInit(): void {
    this.setTopicMap( );
    this.form = new FormGroup({});
    this.form.addControl('topicSelect', new FormControl());
    this.getContentItems( this.contentTypes, this.areaId, this.locale );
  }
```
... and then in the returned `Promise `I'm executing a function to set the options. First, set the parent list of all content items to be downloaded, as well as the subset of items to be shown when filtered by `ng-select` (the same as the parent list to begin with), then set `preselections `for `ng-select` as an array of values (this is hidden in `getSelectOptions`. Then make available only those choices in `ng-select` that are relevant to the particular content that was download, and then preselect a subset of options in `initializeForm`.
```
  getContentItems( ct: string, a: string, l: string ): void {
    this.contentItemService.getContentItems(ct, a, l)
      .then((data) => this.filteredItems = this.contentItems = this.getArrayFromPayload(data))
      //this.preselections set below to be an array of values, should probably make this its own function
      .then((ci) => this.selectOptions = this.getSelectOptions(ci, this.topicMap)) 
      .then(() => this.initializeForm());
  }

  initializeForm( ): void {
    if( this.topicFilter.length ) {
      this.form.controls['topicSelect'].setValue(this.preselections);
    }
  }
```
And then at some point I'm getting the message that `optionsDict[item]` is undefined and has no `selected` property. This is happening during `setValue`, I believe.

**Comment by KyleCartmell** [comment]
I saw this message while I was integrating the component. I believe it was because my options set was undefined for a short time before my async call to the server to fetch the options set completed. I corrected the issue by initializing options as an empty array prior to the arrival of the actual options set. HTH!

**Comment by dcoli** [comment]
Did you initialize the options by creating an empty public variable in the component class and then assigning it to the [options] attribute in your template? That's what I'm doing, but I feel it might need to be assigned in the class itself, along with new FormGroup, new FormControl, etc. I don't see any documentation on how to do that. 

With my breakpoint I determined that the options disappear right at the time I need to set them as selected, similar probably to what you were seeing.

**Comment by KyleCartmell** [comment]
If I'm following, then yes; I initialize `public options = []` in my component and the template sets options="options". I'm using only template syntax and no reactive form bits such as FormGroup or FormControl. I struggled a bit with integration because of quirks like this, but in the end all I needed to do was add ng-select to my template and correctly map the options and ngModel attributes.

**Comment by dcoli** [comment]
Hmmm... if you are not using reactive forms then how are you setting the preselected items?

**Comment by KyleCartmell** [comment]
I set the values in ngModel.

**Comment by matthewhegarty** [comment]
I can set the value in an `ngOnInit()` block, in a Promise return, for a reactive form, but I have to use this trick:

```
        setTimeout(() => {
            this.contactsForm.controls['contactType'].setValue(someVal);
        }, 0);
```

This hack is referred to (for form resets) in the [Angular docs](https://angular.io/docs/ts/latest/guide/forms.html).

**Comment by simonwiles** [comment]
What about if the component is deployed outside a form context?  Is there any way of setting an initial value in this case?

**Comment by tgiordmaina** [comment]
Solution with ngModel works for me :+1:  for example :
`<ng-select class="select2-custom-class select2-no-search" [options]="listItem" (selected)="onSelectedItem($event)" [(ngModel)]="currentItem" [ngModelOptions]="{standalone: true}"></ng-select>`

**Comment by ovaiskhan11** [comment]
Can anyone please answer my question ?
http://stackoverflow.com/questions/40582582/angular-2-ng-select-multiple-selected-values-issue

**Comment by basvandenberg** [comment]
Finally I added a section to the README.md showing how to use this component with `ngModel`, which can be used outside of a form (although the FormsModule has to be imported in order to use ngModel). I also added an example using `ngModel` to the plunker. Hopefully this will help.

p.s. @tgiordmaina the `ngModelOptions` are not needed. I think that's an angular 1 thing.

**Comment by tgiordmaina** [comment]
@basvandenberg Thanks for your update of readme.
I missed to delete  `ngMpdelOptions` you right it's not needed on your example (however it's fully angular2 compliant).
I use it because I have your select inside a `formGroup` which raise an error if it missing :  `ngModel cannot be used to register form controls with a parent formGroup directive`.

**Comment by basvandenberg** [comment]
Thanks for the info, I didn't know that.
