### ISSUE TITLE
Unable to start app with the version 1.0.0-alpha.9

### ISSUE THREAD

**Issue by h284611** [basvandenberg/angular2-select#18]
I was using 1.0.0-alpha.9 and got the following error. The error was gone after downgrading to 1.0.0-alpha.6.

I referenced SelectModule in the app.module.ts, and not even used it in my html template.

$ npm start

> xxx-xxx@0.1.0 start /Users/h284611/dev/order
> tsc && concurrently "tsc -w" "lite-server" 

node_modules/@types/node/index.d.ts(102,6): error TS2300: Duplicate identifier 'BufferEncoding'.
node_modules/@types/node/index.d.ts(263,18): error TS2300: Duplicate identifier 'EventEmitter'.
node_modules/@types/node/index.d.ts(549,26): error TS2300: Duplicate identifier 'Buffer'.
node_modules/@types/node/index.d.ts(549,50): error TS2300: Duplicate identifier 'SlowBuffer'.
node_modules/@types/node/index.d.ts(570,18): error TS2300: Duplicate identifier 'EventEmitter'.
node_modules/@types/node/index.d.ts(570,18): error TS2415: Class 'EventEmitter' incorrectly extends base class 'NodeJS.EventEmitter'.
  Types of property 'eventNames' are incompatible.
    Type '() => (string | symbol)[]' is not assignable to type '() => string[]'.
      Type '(string | symbol)[]' is not assignable to type 'string[]'.
        Type 'string | symbol' is not assignable to type 'string'.
          Type 'symbol' is not assignable to type 'string'.
node_modules/@types/node/index.d.ts(681,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'httpVersionMajor' must be of type 'string', but here has type 'number'.
node_modules/@types/node/index.d.ts(682,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'httpVersionMinor' must be of type 'string', but here has type 'number'.
node_modules/@types/node/index.d.ts(683,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'connection' must be of type 'any', but here has type 'Socket'.
node_modules/@types/node/index.d.ts(733,18): error TS2300: Duplicate identifier 'Agent'.
node_modules/@types/node/index.d.ts(788,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'addressType' must be of type 'string', but here has type 'number | "udp4" | "udp6"'.
node_modules/@types/node/index.d.ts(791,18): error TS2300: Duplicate identifier 'Worker'.
node_modules/@types/node/index.d.ts(1377,17): error TS2300: Duplicate identifier 'CompleterResult'.
node_modules/@types/node/index.d.ts(1414,18): error TS2300: Duplicate identifier 'Script'.
node_modules/@types/node/index.d.ts(2320,18): error TS2451: Cannot redeclare block-scoped variable 'constants'.
node_modules/@types/node/index.d.ts(2550,18): error TS2300: Duplicate identifier 'TLSSocket'.
node_modules/@types/node/index.d.ts(2861,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
node_modules/@types/node/index.d.ts(2862,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
node_modules/@types/node/index.d.ts(2863,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
node_modules/@types/node/index.d.ts(2864,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
node_modules/@types/node/index.d.ts(2865,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
node_modules/@types/node/index.d.ts(3216,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(3299,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(3321,18): error TS2300: Duplicate identifier 'Domain'.
node_modules/@types/node/index.d.ts(3613,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(3639,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(78,6): error TS2300: Duplicate identifier 'BufferEncoding'.
typings/globals/node/index.d.ts(234,18): error TS2300: Duplicate identifier 'EventEmitter'.
typings/globals/node/index.d.ts(518,9): error TS2502: 'BuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(519,9): error TS2502: 'SlowBuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(520,26): error TS2300: Duplicate identifier 'Buffer'.
typings/globals/node/index.d.ts(520,50): error TS2300: Duplicate identifier 'SlowBuffer'.
typings/globals/node/index.d.ts(541,18): error TS2300: Duplicate identifier 'EventEmitter'.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'addListener' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'emit' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'on' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'once' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'prependListener' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(582,22): error TS2320: Interface 'Server' cannot simultaneously extend types 'EventEmitter' and 'Server'.
  Named property 'prependOnceListener' of types 'EventEmitter' and 'Server' are not identical.
typings/globals/node/index.d.ts(703,18): error TS2300: Duplicate identifier 'Agent'.
typings/globals/node/index.d.ts(748,18): error TS2300: Duplicate identifier 'Worker'.
typings/globals/node/index.d.ts(1141,22): error TS2300: Duplicate identifier 'CompleterResult'.
typings/globals/node/index.d.ts(1181,18): error TS2300: Duplicate identifier 'Script'.
typings/globals/node/index.d.ts(1848,18): error TS2451: Cannot redeclare block-scoped variable 'constants'.
typings/globals/node/index.d.ts(2076,18): error TS2300: Duplicate identifier 'TLSSocket'.
typings/globals/node/index.d.ts(2308,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
typings/globals/node/index.d.ts(2309,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
typings/globals/node/index.d.ts(2310,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
typings/globals/node/index.d.ts(2311,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
typings/globals/node/index.d.ts(2312,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
typings/globals/node/index.d.ts(2536,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(2619,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(2641,18): error TS2300: Duplicate identifier 'Domain'.
typings/globals/node/index.d.ts(2933,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(2959,5): error TS2300: Duplicate identifier 'export='.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! order@0.1.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the order@0.1.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the work-order package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "tsc -w" "lite-server" 
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs work-order
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls work-order
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/h284611/dev/order/npm-debug.log

**Comment by basvandenberg** [comment]
This should be fixed in alpha.10, please let me know if not.
