### ISSUE TITLE
RC.6 issues

### ISSUE THREAD

**Issue by predatorkill** [basvandenberg/angular2-select#2]
I m using angular-cli `1.0.0-beta.11-webpack.8` and RC6.

I get this console error:

`select.component.js:15 Uncaught TypeError: core_1.Provider is not a constructor`

thee are the code lines:

`exports.SELECT_VALUE_ACCESSOR = new core_1.Provider(forms_1.NG_VALUE_ACCESSOR, {
    useExisting: core_1.forwardRef(function () { return SelectComponent; }),
    multi: true`

any idea what is going on?

Thanks

**Comment by predatorkill** [comment]
My guess is that this breaking change occured in RC6:

`core: These forms of providers are no longer accepted:

bind(MyClass).toFactory(...)
new Provider(MyClass, toFactory: ...)

We now only accept:

{provider: MyClass, toFactory: ...}`

**Comment by basvandenberg** [comment]
Sorry, at the moment I cannot have a look at it because I am on vacation. I will do this as soon as I get back (in about two weeks).

**Comment by dipolediamond** [comment]
Will also need to update the peer dependencies
"angular2-select@1.0.0-alpha.4 requires a peer of @angular/forms@^0.3.0" and RC6 uses forms@2.0.0-rc.6

**Comment by basvandenberg** [comment]
The update to angular 2.0.0, the updated dependencies, and @dipolediamond 's fix should resolve the issue.
