### ISSUE TITLE
There's anyway to add validation

### ISSUE THREAD

**Issue by diegounanue** [basvandenberg/angular2-select#20]
There's anyway to add validation - like required?

**Comment by basvandenberg** [comment]
Yes, you can add a validator to this component if you use it as FormControl as part of a form. You can use the `Validators.required` but you can also create your own custom validator. If you have a form like this in your template:

```
<form
    [formGroup]="form">

    <ng-select
        [options]="myOptions"
        formControlName="mySelect">
    </ng-select>
</form>
```

 To use `Validators.required` import the `Validators` from the `forms` module:

```
import {FormControl, FormGroup, Validators} from '@angular/forms';
```

And provide the `required` validator as second argument of your angular2-select `FormControl`.

```
ngOnInit() {
    this.form = new FormGroup({});
    this.form.addControl('mySelect', new FormControl('', Validotars.required));
}
```

In your template you could now for example disable a button as long as no item is selected (as long as the form is invalid):

```
<button
    [disabled]="form.invalid">
    Do something
</button>
```

I will add this example to the demo-app and plunker later.
