### ISSUE TITLE
deselected() never fires in single select

### ISSUE THREAD

**Issue by matthewhegarty** [basvandenberg/angular2-select#23]
Using `1.0.0-alpha.10`.

deselected() never fires.  This is visible in the [Plunkr](https://plnkr.co/edit/JcG8uO9nIfSGMEKdLf0Y?p=preview) example.

Simply select an item, then choose another.  All events fire (selected, opened, closed) but 'deselect' never does.

**Comment by basvandenberg** [comment]
This should be fixed with the latest commit ([d896c69] (https://github.com/basvandenberg/angular2-select/commit/d896c69afbbd69d7312d94750265bbc1fe3aec71)).
