### ISSUE TITLE
'touched' property of FormControl never changes for single select

### ISSUE THREAD

**Issue by matthewhegarty** [basvandenberg/angular2-select#24]
Add the following to the example:

`<p style="color: red">touched: {{form.controls['selectSingle'].touched}}</p>`

This 'touched' value will remain false even when you click elements within the select.  

[Plunkr](https://embed.plnkr.co/VLxTI5dhzUsMQ78sG7vc/)

Using `1.0.0-alpha.10`.

**Comment by basvandenberg** [comment]
Yes, you're right, I still need to add the call('s) to the [onTouched](https://angular.io/docs/ts/latest/api/forms/index/DefaultValueAccessor-directive.html#!#onTouched-anchor) function. Is on the to-do list.

**Comment by basvandenberg** [comment]
Should work in the beta version.
