### ISSUE TITLE
How do I access the callback on the clear button?

### ISSUE THREAD

**Issue by purplyrocky** [basvandenberg/angular2-select#26]
May I have a few lines of documentation on how to access the callback for the clear filter button please?

**Comment by basvandenberg** [comment]
With the 'clear filter button' I assume that you mean the little cross you see in the single select dropdown if an item is selected, right? The one that clears the currently selected item.

In the next release (`alpha.11`) the `deselected` event will be triggered if you click this cross. You can bind to this event as follows:
```
<!-- somewhere in your template -->
<ng-select
    [options]="options"
    (deselected)="onDeselected($event)">
</ng-select>
```
And handle the event in your corresponding component class:
```
onDeselected(item) {
    console.log('Deselected: ' + item.value + ', ' + item.label);
}
```
Does that answer your question?

**Comment by purplyrocky** [comment]
Yes, I've tried using the (deselected) in my template and created an event handler in my component exactly how you did in your example however my `onDeselected()` function doesn't get called when I click the `X`. Are you saying that it won't work until your alpha.11 release?

**Comment by basvandenberg** [comment]
I just released [`alpha.12`](https://github.com/basvandenberg/angular2-select/releases/tag/1.0.0-alpha.12). In that release the `deselected` event works for the single select case. In `alpha.11` it does not work yet.

**Comment by purplyrocky** [comment]
Awesome, thank you!! 💥
