### ISSUE TITLE
Empty string value

### ISSUE THREAD

**Issue by inzerceubytovani** [basvandenberg/angular2-select#31]
After deselect options value is set to empty string : "" instead of empty array []

**Comment by basvandenberg** [comment]
It is set to empty string for a reason, namely that the RequiredValidator sees this as empty value, and an empty list not.

If set to an empty list (which was the case before) the form will be valid, even if the RequiredValidator is added as validator to the select form control. 

I agree that this is not nice, but I don't see how else to solve this at the moment.
