### ISSUE TITLE
Select with image

### ISSUE THREAD

**Issue by theunreal** [basvandenberg/angular2-select#33]
Is it possible to add an icon to each item from the angular2-select list?

**Comment by basvandenberg** [comment]
No, only text labels are supported at the moment. It is on my list, but I am not sure if this will be added soon. I am pretty busy at the moment, I can hardly find the time to work on this project.

You might want to keep track of the [material2 select component](https://github.com/angular/material2/tree/master/src/lib/select) that is currently being developed. I expect that it won't take them long to release the first version, and they will support this.

**Comment by basvandenberg** [comment]
Closing this issue for now, because of the low priority.
