### ISSUE TITLE
How I display selected options in the ng-select?

### ISSUE THREAD

**Issue by ovaiskhan11** [basvandenberg/angular2-select#34]
I have an array and I want to show some default selected options in the ng-select

Can you please tell me how I display selected options in the ng-select?

**Comment by basvandenberg** [comment]
Please have a look at the examples in the documentation

https://github.com/basvandenberg/angular2-select#use-with-ngmodel

https://github.com/basvandenberg/angular2-select#use-in-reactive-forms
