### ISSUE TITLE
question: add item to list

### ISSUE THREAD

**Issue by figuerres** [basvandenberg/angular2-select#36]
can the "not found" event be changed to add adding a value to the list ?
I am trying to see where and how to make that happen.

**Comment by basvandenberg** [comment]
I don't understand what you mean exactly. I am not aware of a "not found" event. Could you please explain your issue/feature request in a bit more detail?

**Comment by basvandenberg** [comment]
Closing this issue for now. Please provide more information if you want to have it reopened.
