### ISSUE TITLE
Question: Can i use it with Webpack? If "yes", how can i do?

### ISSUE THREAD

**Issue by BCaldas** [basvandenberg/angular2-select#38]

**Comment by matthewhegarty** [comment]
If it helps I am using angular-cli (which uses webpack) and it works fine.

**Comment by basvandenberg** [comment]
It indeed works with angular-cli, so it should be possible with webpack. But I never tried and never used webpack, so I can't help you with this.

**Comment by Meligy** [comment]
For Angular CLI I just installed the library via NPM and added the select module into my `NgModule` `imports`, and that was it. No special config required in `angular-cli.json` or anywhere else.

So, most probably for webpack scenarios no special config is needed. Just import it and roll.
