### ISSUE TITLE
Exception/Fix

### ISSUE THREAD

**Issue by queejie** [basvandenberg/angular2-select#39]
I had an exception and had to put in a fix in the writeValue method:

               SelectComponent.prototype.writeValue = function (value) {
                      ....
                       else if (value !== '') {
                           if (typeof this.optionsDict[value] == 'undefined') { 
				  this.optionsDict[value] = {}; 
                           } // queejie - comes up undefined on initialization
                           this.optionsDict[value].selected = true;
                       }
                       ...
                   };

Not sure if this is due to something I was doing wrong in setting it up in the view constructor:

               for (let organization of this.organizations) {
                    this.orgSelectOptions.push({value: organization.id, label: organization.code + ' ' + organization.name});
                }

**Comment by basvandenberg** [comment]
Where in your code is the for loop that populates the options list? Doing this in the `ngOnInit` function might cause this error. In that case you could try to add the for loop in the `ngAfterViewInit` lifecycle hook function.

**Comment by queejie** [comment]
Thank you.  I tried it as you suggested, in `ngAfterViewInit`, but have the same errors.

```
import {Component} from "@angular/core";
import {NavController} from "ionic-angular";
import {OrganizationProvider} from "../../providers/organization";
import {OrganizationDetailPage} from "./detail";
import {DataModel} from "../../providers/data-model";

@Component({
    templateUrl: 'list.html'
})
export class OrganizationListPage {
    organizations = [];
    queryText: string = '';

    constructor(private nav: NavController, private organizationData: OrganizationProvider) {
    }

    ngAfterViewInit() {
        let organizationId = 0;
        let drilldown = 1;
        let includeInactive = 0;
        let args = [organizationId, drilldown, includeInactive];
        this.organizationData.getAll(DataModel.buildArgs(args), false).then(organizations => {
            this.organizations = organizations;
            for (let organization of this.organizations) {
                organization.visible = true;
            }
        });
    }

    goToDetail(organization) {
        this.nav.push(OrganizationDetailPage, organization);
    }

}```

**Comment by Koeroesi86** [comment]
I've just added ` || value === false` which seems to be the default value.

You can use this as a quickfix in your code as well:
```javascript
SelectComponent.prototype.writeValue = function (value: any) {
    if (typeof value === 'undefined' || value === null || value === '' || value === false) {
        value = this.multiple ? [] : '';
    }
    for (var item in this.optionsDict) {
        if(this.optionsDict[item]) {
            this.optionsDict[item].selected = false;
        }
    }
    if (this.multiple) {
        for (var _i = 0, value_1 = value; _i < value_1.length; _i++) {
            var item = <string>(value_1[_i]);
            this.optionsDict[item].selected = true;
        }
    }
    else if (value !== '') {
        this.optionsDict[value].selected = true;
    }
    this.updateSelection();
};
```

If you could please remove core-js reference as well that would help a lot as well, because it gives reference error.
