### ISSUE TITLE
Executing a method onSelect

### ISSUE THREAD

**Issue by theunreal** [basvandenberg/angular2-select#4]
Is it possible to execute a method after the user makes a selection?
For example:

```
<ng-select *ngIf="data" [allowClear]="false"
              [options]="data"
			  (selected)="selected($event)"
              placeholder="Choose data"
			  >
  </ng-select>
```

the $event is the object **value** and **label**

An example use will be when someone needs to select an user from the select box and execute a method to load the user data from an API once the user has chosen from the box

**Comment by basvandenberg** [comment]
Thanks for raising this missing feature @theunreal, it was on my list for some time already, but I didn't have much time to spend on this project lately.

I just added output events `opened`, `closed`, `selected`, and `deselected` (see [events](https://github.com/basvandenberg/angular2-select#events) documentation). The `selected` event is exactly the one you asked for, it provides you with the selected item (object with `value` and `label`).
