### ISSUE TITLE
Open from ts.

### ISSUE THREAD

**Issue by Dominionys** [basvandenberg/angular2-select#43]
Hi,

I have ng-select in html and i want to open it from my component. Is it possible?

**Comment by kalmargabor** [comment]
A couple of callable methods for common operations would be great, for example: open(), close() etc. Is there a(n even hacky) way to do these now?

**Comment by kmolerov** [comment]
Why do you need to open it? I think that this logic should be encapsulated inside the ng-select directive.
If you need something special, maybe it should be added in component as a functionality, or maybe you need different kind of component. 
You should explain your use-case/ux in details.

**Comment by kalmargabor** [comment]
I was adding keyboard support to a form, and I wanted to open the ng-select, when users use the TAB key to jump between inputs, and the focus gets to an ng-select.

**Comment by basvandenberg** [comment]
To provide programmatic access, an open and close function will be available in the beta release. 

Some keyboard support for opening and closing is already present though. If you tab until the select component has focus (shows outline), then you can open it by pressing `Enter` or `Tab+arrow down`. If it's opened, you can close it by pressing `Escape` or `Tab+arrow up`.

**Comment by basvandenberg** [comment]
The beta release has an `open` and `close` function.

**Comment by jurzyna** [comment]
I can not find a way to run this function on the component. @basvandenberg Can you point me to the documentation or examples?
