### ISSUE TITLE
How can I remove default Search by items?

### ISSUE THREAD

**Issue by kobvel** [basvandenberg/angular2-select#44]
What is the easiest way to remove first select value, which is filter search? #

**Comment by basvandenberg** [comment]
Hiding the filter input (like in [select2](https://select2.github.io/examples.html#hide-search)) is planned for the beta release.

**Comment by brandonreid** [comment]
You can also hide it with styles. With default ViewEncapsulation you'd do something like...
`:host /deep/ ng-select .select2-search { display: none; }`

**Comment by basvandenberg** [comment]
I think that hiding the input field will cause errors in the current version, because the component tries to put focus on that input field as soon as the drop down opens.

**Comment by basvandenberg** [comment]
The beta release has a `noFilter` property, see https://basvandenberg.github.io/angular2-select (at the bottom) for examples.

This is a number property, for example [noFilter]="10", in which case the filter will be hidden if there are 10 or less options.
