### ISSUE TITLE
Add Bootstrap style to select box

### ISSUE THREAD

**Issue by SachinSharmaEarthport** [basvandenberg/angular2-select#47]
Hello there,

For the ng-select is it possible to make it display like a Bootstrap form control.  For example on my page I have a bootstrap select box with the label 'Status' created with the HTML:

                <select class="form-control">
                    <option value="Action1">Action1</option>
                </select>

On the same page I have an ng-select with label 'Bank accounts(s)' and 'Client'.  See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/24301036/20806307/52745d26-b7f2-11e6-82ce-4606aec92e4a.png)

For the 'Bank accounts(s)' and 'Client' ng-select is it possible to give it the same bootstrap styling as the 'Status' select box i.e.- the border?  Or is there a work around?  This is for consistency on my form.

**Comment by basvandenberg** [comment]
There is no bootstrap theme styling available. You could change the styling with CSS though. It should for example be possible to increase the border radius of the multiple select with by adding the following rule to a global style sheet.

```
ng-select .select2-container--default.select2-container--focus .select2-selection--multiple {
    border-radius: 4px
}
```

But this requires a bit of CSS expertise. You'll have to find out what the existing style rule is (using chrome developer tools for example) and then override this rule by making it more specific.

**Comment by SachinSharmaEarthport** [comment]
Ok I see.  Thank you for getting back to me.
