### ISSUE TITLE
Placeholder text when multiple is false

### ISSUE THREAD

**Issue by SachinSharmaEarthport** [basvandenberg/angular2-select#48]
Hello,

I am using a the ng-select component as follows so  multi select is disabled.

               <ng-select
                        [options]="merchantOptions"
                        [placeholder]="'Select a Client...'"
                        [(ngModel)]="selectedMerchant">
                </ng-select>

However the placeholder text 'Select a Client...' appears but is not greyed out but black.  If [multiple]="true" then this becomes greyed out but I only require a single selection.  See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/24301036/20834962/d5c523e8-b88f-11e6-9b5c-6df5f5dc9e15.png)

**Comment by basvandenberg** [comment]
That's not right indeed. I'll update that. As a temporary fix you can add a custom style rule that changes the color. It seems that I accepted a bit to much style changes in one of the pull requests, sorry about that.

As a temporary fix you could add the following rule to some global style sheet. That should fix it as well.

```
ng-select .select2-container--default .select2-selection--single .select2-selection__placeholder {
    color: #999
}
```

**Comment by SachinSharmaEarthport** [comment]
Thank you for the update.  Do you know when this is likely to be fixed?

Thanks.

**Comment by basvandenberg** [comment]
Fixed in beta version.
