### ISSUE TITLE
How to select only string values?

### ISSUE THREAD

**Issue by kolkov** [basvandenberg/angular2-select#49]
Hi!
Is it possible to get comma separated string values only?
for examle:
`a,b,c,d`
I need this to store into database SET field.

**Comment by basvandenberg** [comment]
No, that is not possible. But you can easily create them yourself.

The value you get back is either an empty string (if nothing is selected), or an array with strings (the values of the selected options). You can easily transform the list of strings to a comma-separated string with the `join` function.

```
// let's say you have the value is stored in selectValue.

let commaSeparated = selectValue === '' ? '' : selectValue.join(',')
```
