### ISSUE TITLE
Clear selected items

### ISSUE THREAD

**Issue by inzerceubytovani** [basvandenberg/angular2-select#5]
First i want to thank you so much for this plugin, it;'s great.

In one case of my use I would like to clear all selected items (because I reload options and I don't want to have selected options which are no longer in possible options).

I tried use` myForm.controls['myControl'].setValue(null) ` but it didn't work.

Any solutions? Thanks

**Comment by basvandenberg** [comment]
I haven't tested it yet, but this should be possible with the function `clearSelected`:

`myForm.controls['myControl'].clearSelected()`

The API functions are not yet documented, because they will still be changed here and there. For example, the function `clearSelected` will be renamed to `clear`. I will try to have these changes and documentation in place by the end of the week.

**Comment by inzerceubytovani** [comment]
Thank you for advice ,  I couldn't call it on FormControl object, but I made a ViewChild reference on component and then call it without problems:

`@ViewChild('myselect')`
`	myselect;`
`this.myselect.clearSelected();`

So that worked but I have one more problem. When I change options, selected options are cleared. But then when i call myForm.controls['myControl'].setValue(newValues) to reinit my form with new values after some action, it shows error - TypeError: Cannot set property 'selected' of undefined - it's in case when I selected some value which wasn't first between selected options but appears later after some action.

It looks like component field `optionsDict` is not updated when my options is updated. But new options are displayed correctly in list. I don'nt know if it's some bug or I'm doing something wrong.

I describe problem in my example:
My options list array depends on other input value. When  I change value, I want to clear selected list to ensure that old options which are not in new possible options will not be selected - I want force user to select options again. That works great with clearSelected. But then I have some insurance to fill form again with stored values (after submit). This is situation when problem appears, because it said that selected values are not in your `optionsDict `array list.

**Comment by basvandenberg** [comment]
My first response was a little hasty, now I had some more time to look at it now. 

First about the `setValue`. There was a bug that caused the `setValue` to behave wrongly, that is fixed  and will be in the next release. If you are using the select module inside a form, you can use one of the following to clear the selection:

myForm.controls['myControl'].setValue()
myForm.controls['myControl'].setValue(null)
myForm.controls['myControl'].setValue('')

The API call `clearSelected` (which will become `clear`) is added for the case that the module is used outside of a form.

**Comment by basvandenberg** [comment]
About the second issue, updating the list of options. I made a test case where I clear the selection and then update the list of options, this works correctly for me. I think the same bug was causing this issue.

The situation where the list of options is updated without clearing the current selection is not handled correctly yet. In this case the current selection will still be shown, but as soon as you select something new, the old selection will disappear and only one item will be selected.

The desired situation is that the selected items that are not in the list of options anymore will be replaced, while those that still are one of the options will stay in the selection.

**Comment by basvandenberg** [comment]
Both EDIT and EDIT2 are both unrelated bugs. Could you please file those as new issues? So that I can refer to those issues separately when I commit their fixes to the git repository. Thanks!

And thanks for the input! That really helps me a lot. I'm sorry that the development is not going very fast, but I don't have that much spare time. For now the software is really alpha... there will still be a lot of bugs in there.

**Comment by inzerceubytovani** [comment]
Great to hear this news. I think that second issue will be fixed after I clear form control with setValue. Also I fighted with another issue when I didn't display select until I have some options in array but also i needed to clear it before new items are in. Problem was that RefElement with # link (to get to DOM element) was undefined when the select wasn't displayed . So this solution helps me also with this problem - I can use form Control and don't have to work with element reference. That's really cool.

I uderstand this is alpha and Im really thankful for your help.
