### ISSUE TITLE
ERROR with @types/core-js

### ISSUE THREAD

**Issue by guillermo-serfe** [basvandenberg/angular2-select#57]
Hi, I've the following errors:

[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:21:14 
    Duplicate identifier 'PropertyKey'.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:85:5 
    All declarations of 'name' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:145:5 
    Subsequent variable declarations must have the same type.  Variable '[Symbol.unscopables]' must be of type '{ copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: ...', but here has type 'any'.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:262:5 
    All declarations of 'flags' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:276:5 
    All declarations of 'EPSILON' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:311:5 
    All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:318:5 
    All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:457:5 
    Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Symbol"', but here has type 'string'.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:457:5 
    All declarations of '[Symbol.toStringTag]' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:464:5 
    All declarations of 'prototype' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:492:5 
    All declarations of 'hasInstance' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:498:5 
    All declarations of 'isConcatSpreadable' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:504:5 
    All declarations of 'iterator' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:510:5 
    All declarations of 'match' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:516:5 
    All declarations of 'replace' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:522:5 
    All declarations of 'search' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:528:5 
    All declarations of 'species' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:534:5 
    All declarations of 'split' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:540:5 
    All declarations of 'toPrimitive' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:546:5 
    All declarations of 'toStringTag' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:552:5 
    All declarations of 'unscopables' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:609:5 
    Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"Math"', but here has type 'string'.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:609:5 
    All declarations of '[Symbol.toStringTag]' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:613:5 
    Subsequent variable declarations must have the same type.  Variable '[Symbol.toStringTag]' must be of type '"JSON"', but here has type 'string'.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:613:5 
    All declarations of '[Symbol.toStringTag]' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:628:5 
    All declarations of 'size' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:634:5 
    All declarations of 'prototype' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:645:5 
    All declarations of 'size' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:651:5 
    All declarations of 'prototype' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:666:5 
    All declarations of 'prototype' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:680:5 
    All declarations of 'prototype' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:692:5 
    All declarations of 'value' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/@types/core-js/index.d.ts:804:5 
    All declarations of 'prototype' must have identical modifiers.
[default] /home/vagrant/code/Application/node_modules/typescript/lib/lib.es2015.core.d.ts:17:14 
    Duplicate identifier 'PropertyKey'.

Can anyone help me? I've already excluded 'core-js' from 'types' and the file index.d.ts on tsconfig.json, but the errors still appearing.

Thanks a lot!

**Comment by matthewhegarty** [comment]
You possibly have a clash because the core-js type spec is defined in `@types/core-js` and somewhere else (`typescript/lib`).  Try to move `@types/core-js` out of the way and see if that helps.

Plus have a read through [this issue](https://github.com/basvandenberg/angular2-select/issues/27)

**Comment by guillermo-serfe** [comment]
@matthewhegarty Thanks for the response.

I can't remove @types/core-js, my idea is to ignore it on tsconfig. Is that possible? 
I've already excluded 'core-js' from 'types' array and the file index.d.ts on tsconfig.json. 
It was working, but when I installed this component they appeared again.

Thanks in advance for the help.

**Comment by matthewhegarty** [comment]
Basically you need to have the core-js types installed in one place only.

You could try to remove your `node_modules` directory then:

```
npm cache clean
npm install
```

Can you get the [demo app](https://github.com/basvandenberg/angular2-select-demo) working?  If so, then you could try to duplicate the config there.  Checkout this [PR](https://github.com/matthewhegarty/angular2-select-demo/commit/b385984f65553f06fc48591da34c78ccf80d30b5), because these are the changes I had to make to solve my issue described in the [issue](https://github.com/basvandenberg/angular2-select/issues/27) above.

I only got the 'duplicate' issue you described when I had both `typings` and `@types/core-js` installed.

**Comment by guillermo-serfe** [comment]
I solved the issue doing these modifications on tsconfig.json:

{
  "compilerOptions": {
       "target": "es5",
       "lib": ["es5"] --> (I had it on "es6")
   }
}

Then "core-js" can be included on "types" array.

Thanks!

**Comment by basvandenberg** [comment]
The `@types/core-js` is no longer a dependency in `package.json`. Hopefully that resolves this issue.
