### ISSUE TITLE
OverLapping dropdowns

### ISSUE THREAD

**Issue by parthghiya** [basvandenberg/angular2-select#58]
If i have two drop downs in my page, i open the second drop down & Then open the first drop down the first drop down overlaps on the second drop down. Any Suggestions ?

**Comment by parthghiya** [comment]
for anyone having the same issue, 
I used @viewChild /@viewChildren to capture other dropdowns & then called the close event of it.

**Comment by SachinSharmaEarthport** [comment]
@parthghiya Could you send an example of this code please?  I am trying to do the same thing.

**Comment by parthghiya** [comment]
Suppose there are 2 select boxes
one with id-1
other with id-2

//Snippet for closing dropdown 2 on opening of dropdown 1 

 template.html
 
 <ng-select #id-1
	(opened)="drpDown1Opened()"
	//other options>
 </ng-select>
 
 <ng-select #id-2
	//other options>
 </ng-select>
 
 app.component.ts
 
 @ViewChild('id-2') id-1:ElementRef; 
 
 //click event to close dropdown2 on open of dropdown 1
 drpDown1Opened(){
    this.renderer.invokeElementMethod(this.id-2,'close',[]);
  }

**Comment by basvandenberg** [comment]
In the upcoming beta release this issue should be resolved. Opening a select dropdown will close all others on the same page.

**Comment by SachinSharmaEarthport** [comment]
@basvandenberg When is this beta likely to be release?

**Comment by basvandenberg** [comment]
I will try to release it this weekend (8th Jan), even though not everything I wanted to have in there is finished. But this issue will be solved in that release.

**Comment by basvandenberg** [comment]
Dropdowns close when clicked outside and a dropdown closes when losing focus by pressing the tab key. This should solve the issue of overlapping drop downs.
