### ISSUE TITLE
how do i set width ?

### ISSUE THREAD

**Issue by yczf1836** [basvandenberg/angular2-select#59]
<ng-select [ngClass]="'place sccjCode'" [ngStyle]="{ **'width': '150px'**, 'text-align': 'center'}" 
                [multiple]="multi" [options]="myOptions" [(ngModel)]="mySelectValue">

**Comment by basvandenberg** [comment]
I think you need to add `display:block` or `display:inline-block` :

```
<ng-select [ngClass]="'place sccjCode'" [ngStyle]="{'display':'block', 'width': '150px', 'text-align': 'center'}"
[multiple]="multi" [options]="myOptions" [(ngModel)]="mySelectValue">
```

Let me know if this works for you, then I will add this style rule by default for the ng-select element.

**Comment by basvandenberg** [comment]
In the beta version you can uses ngStyle to set the width. See https://basvandenberg.github.io/angular2-select for an example.
