### ISSUE TITLE
changing hover color

### ISSUE THREAD

**Issue by macliems** [basvandenberg/angular2-select#61]
Very nice component!
But how can I change the hover color? This blue doesn't fit my brand. I tried to change it with all kinds of overrides in my css, but to no avail. Help would be very much appreciated.

**Comment by macliems** [comment]
Found the way: changed the color in style.js ..

**Comment by basvandenberg** [comment]
In the beta release there are new properties `highlightColor` and `highlightTextColor` to customize the highlight color.
