### ISSUE TITLE
[Accessibility] - Tooltip not allowing select option with keyboard

### ISSUE THREAD

**Issue by dsoldera** [basvandenberg/angular2-select#62]
Hello,

The Tooltip is not allowing to select a option using the Keyboard.

Please check the image attached.

Could you please help us with this issue ASAP??

Thanks.

![tooltip not working on keyboard](https://cloud.githubusercontent.com/assets/11474555/21311109/a6bd8d52-c5cc-11e6-9551-88f768007fdd.gif)

**Comment by basvandenberg** [comment]
In the [plunker](https://plnkr.co/edit/PeGmCwVmi1X8Ag7LgnPT?p=preview) example I can use the keyboard (press enter key) for selecting an item. On enter press, the currently highlighted option should be selected. So hovering with the mouse over the options and then pressing the enter key should work.

What browser are you using? It might be a cross browser issue.

**Comment by dsoldera** [comment]
Hi @basvandenberg. I´m using Chrome. 

I´ve cheched the plunker and works fine. I´ve made a few CSS changes on the plugin. I will check if this are not changing the behavior.

Thanks for the help. =)
