### ISSUE TITLE
angular2-select not completely works on ie9 and ie10

### ISSUE THREAD

**Issue by gdisanto** [basvandenberg/angular2-select#63]
Hi,
I have just tried the example application provided here: https://github.com/basvandenberg/angular2-select-demo.
It seems that the component doesn't work well on ie9 and ie10. There are some problems here and there, I think the most annoying are:
1) In the multiple choice select it's not possible to delete an element by click on the "x" button.
2) Selecting options by using arrows keyboard doesn't work well.
3) Sometimes the component has an unexpected behavior (I think it's related to the previous bugs).

Have you planned to solve these problems?

**Comment by aecz** [comment]
Jquery select2 works in IE9 and IE10 based on the official demo: https://select2.github.io/examples.html
But it looks like you are not using the library and code it from scratch.

**Comment by basvandenberg** [comment]
Indeed, as the readme states "A **_native_** select component for angular 2, **_based_** on the select2 JQuery plugin".

So written from scratch, and quick and dirty, to have a quick native angular2 component that is similar to the select2 plugin. This also means that many select2 features are [not yet supported](https://github.com/basvandenberg/angular2-select#not-supported).

I do not have Window's running on any of my computers, so currently I can't test this...

**Comment by gdisanto** [comment]
Thanks for your reply Bastiaan. 
I'm not interested in having a quick fix, I just want to know if you have planned to support ie9 and ie10 in the future since they are supported by angular 2.
I tested your demo with a virtual machine, if you want to to give it a try you can legally download the images from this link: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/.

**Comment by basvandenberg** [comment]
I plan to support the same as angular 2 supports, so also ie9 and ie10. But there is no time schedule for this (I develop when I have time and I do not know beforehand how much time I can spend on this little project).

Don't forget to check out the [material2](https://github.com/angular/material2/tree/master/src/lib/select) select component, that might have better ie9 and ie10 support sooner.

**Comment by gdisanto** [comment]
I completely understand, Bastiaan. That makes sense. As I already told you I'm not interested in a quick fix, I'm willing to wait. I can help you testing your fix when you have time to develop it, just let me know.

**Comment by aecz** [comment]
I had time so i debugged it with the demo code :)
Looks like IE doesnt support event.target.dataset.
I found this polyfill: https://github.com/remy/polyfills/blob/master/dataset.js
Works but still gives me an error when initializing in the console but everything seems to work.
Do you accept PR ? We just need to replace dataset in 3 lines :)

**Comment by basvandenberg** [comment]
Yes, a PR is fine.

In the upcoming beta release I am not using the dataset property anymore, so there it anyway shouldn't be an issue.

**Comment by aecz** [comment]
Ok. ill wait for the beta :) The above workaround is good enough for me and no need to duplicate work.

**Comment by gdisanto** [comment]
Hi Bastiaan,
I have been using your beta version for a while and it seems that everything is working properly now.
There is a little graphical issue but I will open a separate ticket for that one.

Thanks for your work!
