### ISSUE TITLE
Single choice select returns array

### ISSUE THREAD

**Issue by kresogalic8** [basvandenberg/angular2-select#66]
Hey guys, I have a problem with single choice select, which returns me an array in a single choice directive. Please take a look below on example that I have, you can see unit and currency is array, but it's a single choice in HTML. 

Am I doing something wrong or this is your issue?

![screen shot 2017-01-09 at 2 54 39 pm](https://cloud.githubusercontent.com/assets/7289406/21768761/a7adbe66-d67b-11e6-8edb-d811d9bca783.png)

**Comment by aboglioli** [comment]
I'm having the same problem!

**Comment by aboglioli** [comment]
I found the problem on [select.component.ts](https://github.com/basvandenberg/angular2-select/blob/master/src/select.component.ts#L246) (line 246)

```javascript
 set value(v: any) {
        if (typeof v === 'undefined' || v === null || v === '') {
            v = [];
        }
        else if (typeof v === 'string') {
            v = [v];
        }

        if (v !== this._value) {
            this._value = v;
            this.optionList.value = v;

            this.hasSelected = v.length > 0;
            this.placeholderView = this.hasSelected ? '' : this.placeholder;
            this.updateFilterWidth();

           // here, v is an array and it's returned to your FormControl below
            this.onChange(v);
        }
    }
```

When you set the value, it is put in an Array. You can have a problem if you:
```javascript
this.form.controls['form-control'].setValue('');
```
If you want to reset an `ng-select` setting your form control value as `''`.

I'm going to see how to solve this and send a pull request.

**Comment by kresogalic8** [comment]
Awesome man, that would be great to resolve this.
