### ISSUE TITLE
Placeholder formatting is different for single vs multi select

### ISSUE THREAD

**Issue by matthewhegarty** [basvandenberg/angular2-select#67]
Minor formatting issue (`1.0.0-beta.1`).  Placeholder text format is different depending on whether multi or single select.  Chrome 53.0.2785.143

In `select.component.html` the single placeholder is in a placeholder div:

```
        <div class="placeholder"
            *ngIf="!optionList.hasSelected()">
            {{placeholderView}}
        </div>
```

Whereas for multiple, the placeholder is assigned to the input:

```
        <input
            *ngIf="filterEnabled"
            #filterInput
            tabindex="-1"
            [placeholder]="placeholderView"
            [ngStyle]="{'width.px': filterInputWidth}"
            (input)="onMultipleFilterInput($event)"
            (keydown)="onMultipleFilterKeydown($event)"/>
```

![angular2-select-formatting](https://cloud.githubusercontent.com/assets/6249838/21770895/2c6206ca-d67d-11e6-9e97-3d51d4fca52f.png)

**Comment by basvandenberg** [comment]
Thanks @matthewhegarty, you have a keen eye for details! And you're absolutely right, I'll have a look at it.

**Comment by basvandenberg** [comment]
Slightly changed color and font-size, they should look the same now. Thanks again!
