### ISSUE TITLE
IE11 all dropdowns is open after ng-model changes.

### ISSUE THREAD

**Issue by gurinderu** [basvandenberg/angular2-select#72]
We use our state loading which changes ng-model property
ON IE11 after change ng-model value all dropdowns are opened. 

angular: 2.4.3
angular2-select: 1.0.0-beta.2
IE:11

**Comment by basvandenberg** [comment]
Now that's an interesting side effect :) Not entirely what it is supposed to do.

Do you have example code? A plunker maybe?

I didn't get to test much with IE, but I did try the [ngModel example](https://basvandenberg.github.io/angular2-select/#value) in IE11, which seemed to work as expected, without opening any drop downs.

**Comment by gurinderu** [comment]
in IE onMultipleFilterInput calls after initialization( because you used  angular (input) event)
We added calling a close method with a timeout, but it is a dirty hack.

Also, we have interest behavior with placeholders in IE

**Comment by basvandenberg** [comment]
It would still be very useful to have a plunker or some example code. Because I am not able to reproduce this issue.

**Comment by basvandenberg** [comment]
Closing this issue because of  no response.
