### ISSUE TITLE
Event when no option is found

### ISSUE THREAD

**Issue by Uniqen** [basvandenberg/angular2-select#73]
I would like to show a create component when the user has searched in options and didn't find they were looking for. It would be nice if an event is emitted when all options has been discarded. Or is this solvable in some other way?

**Comment by basvandenberg** [comment]
Thanks for this suggestion @Uniqen. That sounds like a useful event to add, and that can be added without much effort. I have put it on the desired features list.

**Comment by basvandenberg** [comment]
A `noOptionsFound` output event is implemented, thanks again!

**Comment by Moggieggwp** [comment]
When and in which release it's will be released?
