### ISSUE TITLE
the `onChange` is also called if the set value is the same as the current value

### ISSUE THREAD

**Issue by basvandenberg** [basvandenberg/angular2-select#76]
When a new value is set, it is wrongly checked if this new value is different from the current value. Arrays are checked with `===`, which does not check if the two arrays contain the same strings.

**Comment by DethAriel** [comment]
@basvandenberg Is this in a release already? It also causes the "control.pristine" value to always be "false", which is kinda unexpected. Could you please create a new beta release?
