### ISSUE TITLE
Click on No results found generates error

### ISSUE THREAD

**Issue by inzerceubytovani** [basvandenberg/angular2-select#8]
When I click on text No results found it generates error.

I noticed it also generates error when I accidentally click and drag one option element in opened list to another option element.

Error log:
`core.umd.js:3468 TypeError: Cannot read property 'selected' of undefined at SelectComponent.toggleSelect (select.component.js:165) at SelectComponent.onToggleSelect (select.component.js:75) at DebugAppView._View_SelectComponent6._handle_toggleSelect_0_0 .`

**Comment by basvandenberg** [comment]
Added a fix to resolve this issue.
