### ISSUE TITLE
Problem with selected data

### ISSUE THREAD

**Issue by khoapossible** [basvandenberg/angular2-select#80]
Dear,
I got a problem when loaded data. The ng-select can not set default value. But other can be set default value.
All of ng-select i used same code. But only the last one get problem.
Thank for your support.

![image 3](https://cloud.githubusercontent.com/assets/17254044/22053711/329f29e6-dd85-11e6-8eb3-2a25f4d3ee1d.png)
![image 4](https://cloud.githubusercontent.com/assets/17254044/22053714/35b78592-dd85-11e6-8433-b3447f3b4afc.png)

**Comment by smartHasmukh** [comment]
@khoapossible Can you make plker(Demo) for that issue?

**Comment by basvandenberg** [comment]
Closing this issue because of lacking response. @khoapossible please let me know if you still need help.
