### ISSUE TITLE
Select all

### ISSUE THREAD

**Issue by Nocturnal316** [basvandenberg/angular2-select#81]
I'm attempting to add a select all and clear all options. 

Is there a way to assign a select all button for data that will be loaded on initialization ?

**Comment by cormacrelf** [comment]
See the demo, specifically 'bind to the select value with ngModel'.

```html
<div>
    Value: <strong>{{selectedValues}}</strong>
</div>
<ng-select
    [options]="characters"
    [multiple]="true"
    [(ngModel)]="selectedValues">
</ng-select>
<button
    (click)="selectedValues=['1','3']">
    Select values 1 and 3
</button>
```

That `<button>` element could be bound to `"selectValues=allValues"` if allValues was just the keys of the characters object used as the select options in the demo. (Try _.keys(characters) if you have lodash, or Object.keys(characters), or just whatever the options object's `value` keys are in your own use case.) Same goes for 'clear all': (click)=`"selectedValues=[]"`.

You could also have selectedValues be set initially to all the possible values. The important thing is that 'reset to data that will be loaded on initialization' is something you have to manage yourself using Angular 2's binding mechanisms. The `ng-select` component will never offer the functionality of resetting to its initial value, that is just not how components are built.

**Comment by cormacrelf** [comment]
If you wanted to add this functionality internally, you would need to (obviously) fork angular2-select, but then edit some setters & getters to give the required functionality. E.g. bind a button `(click)="selected=all()" where selected is the internal ngModel (I don't know what this is called) and all() is a method that will get all the values from the [options] that have been passed in.

Some pointers: https://blog.thoughtram.io/angular/2016/10/13/two-way-data-binding-in-angular-2.html

**Comment by Nocturnal316** [comment]
Thank you. I will try to wrap my head around all this and attempt to add the functionality.

**Comment by basvandenberg** [comment]
Assuming that you wrapped your head around it by now :) I'll close the issue for now. Please let me know if you need more help.
