### ISSUE TITLE
Error: No template specified for component SelectComponent

### ISSUE THREAD

**Issue by tsm91** [basvandenberg/angular2-select#85]
Hi @basvandenberg, for some reason i cannot use your select module.

Error is because of: https://github.com/basvandenberg/angular2-select/blame/master/src/select.component.ts#L29
Reference: https://github.com/angular/angular/issues/14010

Commit introduced it: https://github.com/basvandenberg/angular2-select/commit/a2a8970816787403e278631c64dac06ac885b2b5

Version i use: `"angular2-select": "1.0.0-beta.2",`

**Comment by basvandenberg** [comment]
You cannot import the source code, as it is, into your own project. You can see in the [build file](https://github.com/basvandenberg/angular2-select/blob/master/gulpfile.js) (tasks `templates` and `styles`, at the bottom of the file) that the HTML and CSS files are transformed to typescript files. These generated typescript files (containing the HTML and CSS as string variable) are imported into `select.component.ts` and `select-dropdown.component.ts`.

With little adjustments you could import incorporate the source code into your project when using [angular-cli](https://github.com/angular/angular-cli). In `select.component.ts` you should remove:

```
import {STYLE} from './select.component.css';
import {TEMPLATE} from './select.component.html';
```
and replace:
```
@Component({
    selector: 'ng-select',
    template: TEMPLATE,
    styles: [STYLE],
    providers: [SELECT_VALUE_ACCESSOR],
    encapsulation: ViewEncapsulation.None
})
```
with

```
@Component({
    selector: 'ng-select',
    templateUrl: 'select.component.html',
    styleUrls: ['select.component.scss'],
    providers: [SELECT_VALUE_ACCESSOR],
    encapsulation: ViewEncapsulation.None
})
```
The same should be done for `select-dropdown.component.ts`

**Comment by basvandenberg** [comment]
I hope my comment helped. I'll close the issue for now. Please let me know if you need more help.

**Comment by tsm91** [comment]
@basvandenberg hi, sorry for the late ansver

i do not try to import the source code to my own project. i installed it via `npm i --save angular2-select` and did `import { SelectModule } from 'angular2-select'` then imported it in the app module

**Comment by basvandenberg** [comment]
Copying the source is indeed not ideal, but based on your initial issue I thought that you tried to do that.

When installing with npm and importing it as you mentioned there should be no issue with the templates. What does your app.module.ts look like? And what build tool are you using?
