### ISSUE TITLE
Send whole object in value

### ISSUE THREAD

**Issue by kresogalic8** [basvandenberg/angular2-select#89]
Hey guys, is there any possibility to send the whole object in value?

**Comment by basvandenberg** [comment]
No, setting the value can only be done with a string or an Array of strings. If you have objects, then mapping these objects to a list of strings is something you have to do.

**Comment by shujahm** [comment]
@kresogalic8 I have submitted a pull-request where you can send extraData along with the current value & label combination. this will allow you to send your object that you can get back in your click function or any other event handler function.

**Comment by kresogalic8** [comment]
hey @shujahm thanks for that. I just want to send whole object in value, not like now. For example in native select I can say this

```
<select formControlName="location">
    <option *ngFor="let location of customerLocations" [ngValue]="location">{{location.name}}</option>
</select>
```

**Comment by basvandenberg** [comment]
Values have to be string(s), see also #87.
