### ISSUE TITLE
Initial value not set when using reactive forms

### ISSUE THREAD

**Issue by 11mb** [basvandenberg/angular2-select#91]
When I have a reactive form, the initial value in the form-model is not set:

    <form [formGroup]="myForm">
      <fieldset formGroupName="dataSection">
        <ng-select [options]="myOptions" [multiple]="false" formControlName="mySelect">
      </fieldset>
    </form>

    // component:
    public myOptions = [{value: '1', label: 'test1'}, {value: '2', label: 'test2'}];

    ngOnInit() {
      this.myForm= this.fb.group({
          dataSection: this.fb.group({
            mySelect: ['2'],
          })
        });
    }

Expected:
- A selectlist with 'test2' active
- Value in form object for mySelect: '2'

Actual:
- A selectlist with no initial value
- Value in form object for mySelect: '2'

**Comment by matthewhegarty** [comment]
What's the issue?  Your 'Expected' and 'Actual' values are the same.  The example works in [Plunker](https://plnkr.co/edit/XlIsjaSdgaqHB0jLCS9z?p=preview) (initial value `test2` is set)

**Comment by 11mb** [comment]
Sorry, I made a mistake in the bug report. I fixed it. Thanks for looking into this! Your Plunker looks good indeed. I'm going to look into this.
